# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

# Optionally build your docs in additional formats such as PDF
# formats:
#   - pdf

# specify dependencies
python:
   install:
      # - requirements: docs/requirements.txt
      - method: pip
        path: .
        extra_requirements:
        - docs
        # this is where we can tell pip not to install deps
        # (RTD will run `pip install --no-deps -e .[docs]`)
        no_deps: true
